// Code generated by MockGen. DO NOT EDIT.
// Source: reps/basket/basket_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockBasketRepositoryInterface is a mock of BasketRepositoryInterface interface.
type MockBasketRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBasketRepositoryInterfaceMockRecorder
}

// MockBasketRepositoryInterfaceMockRecorder is the mock recorder for MockBasketRepositoryInterface.
type MockBasketRepositoryInterfaceMockRecorder struct {
	mock *MockBasketRepositoryInterface
}

// NewMockBasketRepositoryInterface creates a new mock instance.
func NewMockBasketRepositoryInterface(ctrl *gomock.Controller) *MockBasketRepositoryInterface {
	mock := &MockBasketRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBasketRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketRepositoryInterface) EXPECT() *MockBasketRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockBasketRepositoryInterface) AddItem(ctx context.Context, i structs.BasketItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockBasketRepositoryInterfaceMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockBasketRepositoryInterface) Create(ctx context.Context, b structs.Basket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBasketRepositoryInterfaceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).Create), ctx, b)
}

// DeleteItem mocks base method.
func (m *MockBasketRepositoryInterface) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockBasketRepositoryInterfaceMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).DeleteItem), ctx, id, product_id)
}

// GetBIdByUId mocks base method.
func (m *MockBasketRepositoryInterface) GetBIdByUId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBIdByUId", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBIdByUId indicates an expected call of GetBIdByUId.
func (mr *MockBasketRepositoryInterfaceMockRecorder) GetBIdByUId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBIdByUId", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).GetBIdByUId), ctx, id)
}

// GetById mocks base method.
func (m *MockBasketRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Basket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Basket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBasketRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).GetById), ctx, id)
}

// GetItems mocks base method.
func (m *MockBasketRepositoryInterface) GetItems(ctx context.Context, id_user uuid.UUID) ([]structs.BasketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_user)
	ret0, _ := ret[0].([]structs.BasketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockBasketRepositoryInterfaceMockRecorder) GetItems(ctx, id_user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).GetItems), ctx, id_user)
}

// UpdateItemAmount mocks base method.
func (m *MockBasketRepositoryInterface) UpdateItemAmount(ctx context.Context, basket_id, product_id uuid.UUID, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemAmount", ctx, basket_id, product_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemAmount indicates an expected call of UpdateItemAmount.
func (mr *MockBasketRepositoryInterfaceMockRecorder) UpdateItemAmount(ctx, basket_id, product_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemAmount", reflect.TypeOf((*MockBasketRepositoryInterface)(nil).UpdateItemAmount), ctx, basket_id, product_id, amount)
}
