// Code generated by MockGen. DO NOT EDIT.
// Source: reps/brand/brand_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockBrandRepositoryInterface is a mock of BrandRepositoryInterface interface.
type MockBrandRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBrandRepositoryInterfaceMockRecorder
}

// MockBrandRepositoryInterfaceMockRecorder is the mock recorder for MockBrandRepositoryInterface.
type MockBrandRepositoryInterfaceMockRecorder struct {
	mock *MockBrandRepositoryInterface
}

// NewMockBrandRepositoryInterface creates a new mock instance.
func NewMockBrandRepositoryInterface(ctrl *gomock.Controller) *MockBrandRepositoryInterface {
	mock := &MockBrandRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBrandRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrandRepositoryInterface) EXPECT() *MockBrandRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBrandRepositoryInterface) Create(ctx context.Context, b structs.Brand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBrandRepositoryInterfaceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBrandRepositoryInterface)(nil).Create), ctx, b)
}

// Delete mocks base method.
func (m *MockBrandRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBrandRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBrandRepositoryInterface)(nil).Delete), ctx, id)
}

// GetAllBrandsInCategory mocks base method.
func (m *MockBrandRepositoryInterface) GetAllBrandsInCategory(ctx context.Context, category string) ([]structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrandsInCategory", ctx, category)
	ret0, _ := ret[0].([]structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBrandsInCategory indicates an expected call of GetAllBrandsInCategory.
func (mr *MockBrandRepositoryInterfaceMockRecorder) GetAllBrandsInCategory(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrandsInCategory", reflect.TypeOf((*MockBrandRepositoryInterface)(nil).GetAllBrandsInCategory), ctx, category)
}

// GetById mocks base method.
func (m *MockBrandRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBrandRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBrandRepositoryInterface)(nil).GetById), ctx, id)
}
