// Code generated by MockGen. DO NOT EDIT.
// Source: reps/favourites/favourites_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockFavouritesRepositoryInterface is a mock of FavouritesRepositoryInterface interface.
type MockFavouritesRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFavouritesRepositoryInterfaceMockRecorder
}

// MockFavouritesRepositoryInterfaceMockRecorder is the mock recorder for MockFavouritesRepositoryInterface.
type MockFavouritesRepositoryInterfaceMockRecorder struct {
	mock *MockFavouritesRepositoryInterface
}

// NewMockFavouritesRepositoryInterface creates a new mock instance.
func NewMockFavouritesRepositoryInterface(ctrl *gomock.Controller) *MockFavouritesRepositoryInterface {
	mock := &MockFavouritesRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockFavouritesRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavouritesRepositoryInterface) EXPECT() *MockFavouritesRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockFavouritesRepositoryInterface) AddItem(ctx context.Context, i structs.FavouritesItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockFavouritesRepositoryInterface) Create(ctx context.Context, f structs.Favourites) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) Create(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).Create), ctx, f)
}

// DeleteItem mocks base method.
func (m *MockFavouritesRepositoryInterface) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).DeleteItem), ctx, id, product_id)
}

// GetById mocks base method.
func (m *MockFavouritesRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Favourites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Favourites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).GetById), ctx, id)
}

// GetFIdByUId mocks base method.
func (m *MockFavouritesRepositoryInterface) GetFIdByUId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFIdByUId", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFIdByUId indicates an expected call of GetFIdByUId.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) GetFIdByUId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFIdByUId", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).GetFIdByUId), ctx, id)
}

// GetItems mocks base method.
func (m *MockFavouritesRepositoryInterface) GetItems(ctx context.Context, id_user uuid.UUID) ([]structs.FavouritesItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_user)
	ret0, _ := ret[0].([]structs.FavouritesItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockFavouritesRepositoryInterfaceMockRecorder) GetItems(ctx, id_user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockFavouritesRepositoryInterface)(nil).GetItems), ctx, id_user)
}
