// Code generated by MockGen. DO NOT EDIT.
// Source: reps/order/order_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockOrderRepositoryInterface is a mock of OrderRepositoryInterface interface.
type MockOrderRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryInterfaceMockRecorder
}

// MockOrderRepositoryInterfaceMockRecorder is the mock recorder for MockOrderRepositoryInterface.
type MockOrderRepositoryInterfaceMockRecorder struct {
	mock *MockOrderRepositoryInterface
}

// NewMockOrderRepositoryInterface creates a new mock instance.
func NewMockOrderRepositoryInterface(ctrl *gomock.Controller) *MockOrderRepositoryInterface {
	mock := &MockOrderRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepositoryInterface) EXPECT() *MockOrderRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrderRepositoryInterface) Create(ctx context.Context, o structs.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrderRepositoryInterfaceMockRecorder) Create(ctx, o interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).Create), ctx, o)
}

// Delete mocks base method.
func (m *MockOrderRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockOrderRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetById), ctx, id)
}

// GetFreeOrders mocks base method.
func (m *MockOrderRepositoryInterface) GetFreeOrders(ctx context.Context) ([]structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeOrders", ctx)
	ret0, _ := ret[0].([]structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeOrders indicates an expected call of GetFreeOrders.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetFreeOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeOrders", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetFreeOrders), ctx)
}

// GetItems mocks base method.
func (m *MockOrderRepositoryInterface) GetItems(ctx context.Context, id uuid.UUID) ([]structs.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id)
	ret0, _ := ret[0].([]structs.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetItems(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetItems), ctx, id)
}

// GetOrdersByUser mocks base method.
func (m *MockOrderRepositoryInterface) GetOrdersByUser(ctx context.Context, id uuid.UUID) ([]structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUser", ctx, id)
	ret0, _ := ret[0].([]structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUser indicates an expected call of GetOrdersByUser.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetOrdersByUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUser", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetOrdersByUser), ctx, id)
}

// GetStatus mocks base method.
func (m *MockOrderRepositoryInterface) GetStatus(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetStatus(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetStatus), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockOrderRepositoryInterface) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockOrderRepositoryInterfaceMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).UpdateStatus), ctx, id, status)
}
