// Code generated by MockGen. DO NOT EDIT.
// Source: reps/product/product_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockProductRepositoryInterface is a mock of ProductRepositoryInterface interface.
type MockProductRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryInterfaceMockRecorder
}

// MockProductRepositoryInterfaceMockRecorder is the mock recorder for MockProductRepositoryInterface.
type MockProductRepositoryInterfaceMockRecorder struct {
	mock *MockProductRepositoryInterface
}

// NewMockProductRepositoryInterface creates a new mock instance.
func NewMockProductRepositoryInterface(ctrl *gomock.Controller) *MockProductRepositoryInterface {
	mock := &MockProductRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepositoryInterface) EXPECT() *MockProductRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductRepositoryInterface) Create(ctx context.Context, p structs.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryInterfaceMockRecorder) Create(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Create), ctx, p)
}

// Delete mocks base method.
func (m *MockProductRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Delete), ctx, id)
}

// GetByArticule mocks base method.
func (m *MockProductRepositoryInterface) GetByArticule(ctx context.Context, art string) (structs.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByArticule", ctx, art)
	ret0, _ := ret[0].(structs.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByArticule indicates an expected call of GetByArticule.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetByArticule(ctx, art interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByArticule", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetByArticule), ctx, art)
}

// GetByBrand mocks base method.
func (m *MockProductRepositoryInterface) GetByBrand(ctx context.Context, brand string) ([]structs.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBrand", ctx, brand)
	ret0, _ := ret[0].([]structs.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBrand indicates an expected call of GetByBrand.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetByBrand(ctx, brand interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBrand", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetByBrand), ctx, brand)
}

// GetByCategory mocks base method.
func (m *MockProductRepositoryInterface) GetByCategory(ctx context.Context, category string) ([]structs.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategory", ctx, category)
	ret0, _ := ret[0].([]structs.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategory indicates an expected call of GetByCategory.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetByCategory(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategory", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetByCategory), ctx, category)
}

// GetById mocks base method.
func (m *MockProductRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetById), ctx, id)
}

// GetByName mocks base method.
func (m *MockProductRepositoryInterface) GetByName(ctx context.Context, name string) (structs.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(structs.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetByName), ctx, name)
}
