// Code generated by MockGen. DO NOT EDIT.
// Source: reps/review/review_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockReviewRepositoryInterface is a mock of ReviewRepositoryInterface interface.
type MockReviewRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryInterfaceMockRecorder
}

// MockReviewRepositoryInterfaceMockRecorder is the mock recorder for MockReviewRepositoryInterface.
type MockReviewRepositoryInterfaceMockRecorder struct {
	mock *MockReviewRepositoryInterface
}

// NewMockReviewRepositoryInterface creates a new mock instance.
func NewMockReviewRepositoryInterface(ctrl *gomock.Controller) *MockReviewRepositoryInterface {
	mock := &MockReviewRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepositoryInterface) EXPECT() *MockReviewRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewRepositoryInterface) Create(ctx context.Context, r structs.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewRepositoryInterfaceMockRecorder) Create(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepositoryInterface)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockReviewRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewRepositoryInterface)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockReviewRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockReviewRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockReviewRepositoryInterface)(nil).GetById), ctx, id)
}

// ReviewsForProduct mocks base method.
func (m *MockReviewRepositoryInterface) ReviewsForProduct(ctx context.Context, id_product uuid.UUID) ([]structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewsForProduct", ctx, id_product)
	ret0, _ := ret[0].([]structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewsForProduct indicates an expected call of ReviewsForProduct.
func (mr *MockReviewRepositoryInterfaceMockRecorder) ReviewsForProduct(ctx, id_product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewsForProduct", reflect.TypeOf((*MockReviewRepositoryInterface)(nil).ReviewsForProduct), ctx, id_product)
}
