// Code generated by MockGen. DO NOT EDIT.
// Source: reps/worker/worker_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockWorkerRepositoryInterface is a mock of WorkerRepositoryInterface interface.
type MockWorkerRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRepositoryInterfaceMockRecorder
}

// MockWorkerRepositoryInterfaceMockRecorder is the mock recorder for MockWorkerRepositoryInterface.
type MockWorkerRepositoryInterfaceMockRecorder struct {
	mock *MockWorkerRepositoryInterface
}

// NewMockWorkerRepositoryInterface creates a new mock instance.
func NewMockWorkerRepositoryInterface(ctrl *gomock.Controller) *MockWorkerRepositoryInterface {
	mock := &MockWorkerRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockWorkerRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRepositoryInterface) EXPECT() *MockWorkerRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AcceptOrder mocks base method.
func (m *MockWorkerRepositoryInterface) AcceptOrder(ctx context.Context, id_order, id_user uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptOrder", ctx, id_order, id_user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptOrder indicates an expected call of AcceptOrder.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) AcceptOrder(ctx, id_order, id_user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptOrder", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).AcceptOrder), ctx, id_order, id_user)
}

// Create mocks base method.
func (m *MockWorkerRepositoryInterface) Create(ctx context.Context, w structs.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) Create(ctx, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).Create), ctx, w)
}

// Delete mocks base method.
func (m *MockWorkerRepositoryInterface) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).Delete), ctx, id)
}

// GetAllWorkers mocks base method.
func (m *MockWorkerRepositoryInterface) GetAllWorkers(ctx context.Context) ([]structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWorkers", ctx)
	ret0, _ := ret[0].([]structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWorkers indicates an expected call of GetAllWorkers.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) GetAllWorkers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWorkers", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).GetAllWorkers), ctx)
}

// GetById mocks base method.
func (m *MockWorkerRepositoryInterface) GetById(ctx context.Context, id uuid.UUID) (structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).GetById), ctx, id)
}

// GetOrders mocks base method.
func (m *MockWorkerRepositoryInterface) GetOrders(ctx context.Context, id uuid.UUID) ([]structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, id)
	ret0, _ := ret[0].([]structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockWorkerRepositoryInterfaceMockRecorder) GetOrders(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockWorkerRepositoryInterface)(nil).GetOrders), ctx, id)
}
