FROM golang:1.24.0-alpine AS builder

WORKDIR /app

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download
RUN go install gotest.tools/gotestsum@latest

COPY ./src .

RUN mkdir -p ./internal/database/sql

CMD ["go", "test", "-v", "./internal/integration_tests/... -test.parallel=3 -count=1"]

# , "-cover", "-coverprofile=coverage.out", "-coverpkg=github.com/taucuya/ppo/internal/integration_tests...", 