FROM golang:1.23.6

WORKDIR /app

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download

COPY ./src .

RUN mkdir -p /app/internal/database/sql

CMD ["go", "test", "-v", "-cover", "-coverprofile=coverage.out", "-coverpkg=github.com/taucuya/ppo/internal/repository/postgres/reps/...", "./internal/repository/tests/..."]