FROM golang:1.23.6

WORKDIR /app

COPY ./src/go.mod ./src/go.sum ./
RUN go mod download

COPY ./src .

RUN mkdir -p /app/internal/database/sql

CMD ["go", "test", "-v", "./internal/integration_tests/..."]

# , "-cover", "-coverprofile=coverage.out", "-coverpkg=github.com/taucuya/ppo/internal/integration_tests...", 