// Code generated by MockGen. DO NOT EDIT.
// Source: service/brand/brand.go

// Package mock_structs is a generated GoMock package.
package mock_structs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockBrandService is a mock of BrandService interface.
type MockBrandService struct {
	ctrl     *gomock.Controller
	recorder *MockBrandServiceMockRecorder
}

// MockBrandServiceMockRecorder is the mock recorder for MockBrandService.
type MockBrandServiceMockRecorder struct {
	mock *MockBrandService
}

// NewMockBrandService creates a new mock instance.
func NewMockBrandService(ctrl *gomock.Controller) *MockBrandService {
	mock := &MockBrandService{ctrl: ctrl}
	mock.recorder = &MockBrandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrandService) EXPECT() *MockBrandServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBrandService) Create(ctx context.Context, b structs.Brand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBrandServiceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBrandService)(nil).Create), ctx, b)
}

// Delete mocks base method.
func (m *MockBrandService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBrandServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBrandService)(nil).Delete), ctx, id)
}

// GetAllBrands mocks base method.
func (m *MockBrandService) GetAllBrands(ctx context.Context) ([]structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrands", ctx)
	ret0, _ := ret[0].([]structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBrands indicates an expected call of GetAllBrands.
func (mr *MockBrandServiceMockRecorder) GetAllBrands(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrands", reflect.TypeOf((*MockBrandService)(nil).GetAllBrands), ctx)
}

// GetById mocks base method.
func (m *MockBrandService) GetById(ctx context.Context, id uuid.UUID) (structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBrandServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBrandService)(nil).GetById), ctx, id)
}

// MockBrandRepository is a mock of BrandRepository interface.
type MockBrandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBrandRepositoryMockRecorder
}

// MockBrandRepositoryMockRecorder is the mock recorder for MockBrandRepository.
type MockBrandRepositoryMockRecorder struct {
	mock *MockBrandRepository
}

// NewMockBrandRepository creates a new mock instance.
func NewMockBrandRepository(ctrl *gomock.Controller) *MockBrandRepository {
	mock := &MockBrandRepository{ctrl: ctrl}
	mock.recorder = &MockBrandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrandRepository) EXPECT() *MockBrandRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBrandRepository) Create(ctx context.Context, b structs.Brand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBrandRepositoryMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBrandRepository)(nil).Create), ctx, b)
}

// Delete mocks base method.
func (m *MockBrandRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBrandRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBrandRepository)(nil).Delete), ctx, id)
}

// GetAllBrandsInCategory mocks base method.
func (m *MockBrandRepository) GetAllBrandsInCategory(ctx context.Context, category string) ([]structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBrandsInCategory", ctx, category)
	ret0, _ := ret[0].([]structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBrandsInCategory indicates an expected call of GetAllBrandsInCategory.
func (mr *MockBrandRepositoryMockRecorder) GetAllBrandsInCategory(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBrandsInCategory", reflect.TypeOf((*MockBrandRepository)(nil).GetAllBrandsInCategory), ctx, category)
}

// GetById mocks base method.
func (m *MockBrandRepository) GetById(ctx context.Context, id uuid.UUID) (structs.Brand, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Brand)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBrandRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBrandRepository)(nil).GetById), ctx, id)
}
