// Code generated by MockGen. DO NOT EDIT.
// Source: service/review/review.go

// Package mock_structs is a generated GoMock package.
package mock_structs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockReviewService is a mock of ReviewService interface.
type MockReviewService struct {
	ctrl     *gomock.Controller
	recorder *MockReviewServiceMockRecorder
}

// MockReviewServiceMockRecorder is the mock recorder for MockReviewService.
type MockReviewServiceMockRecorder struct {
	mock *MockReviewService
}

// NewMockReviewService creates a new mock instance.
func NewMockReviewService(ctrl *gomock.Controller) *MockReviewService {
	mock := &MockReviewService{ctrl: ctrl}
	mock.recorder = &MockReviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewService) EXPECT() *MockReviewServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewService) Create(ctx context.Context, r structs.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewServiceMockRecorder) Create(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewService)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockReviewService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewService)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockReviewService) GetById(ctx context.Context, id uuid.UUID) (structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockReviewServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockReviewService)(nil).GetById), ctx, id)
}

// ReviewsForProduct mocks base method.
func (m *MockReviewService) ReviewsForProduct(ctx context.Context, id_product uuid.UUID) ([]structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewsForProduct", ctx, id_product)
	ret0, _ := ret[0].([]structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewsForProduct indicates an expected call of ReviewsForProduct.
func (mr *MockReviewServiceMockRecorder) ReviewsForProduct(ctx, id_product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewsForProduct", reflect.TypeOf((*MockReviewService)(nil).ReviewsForProduct), ctx, id_product)
}

// MockReviewRepository is a mock of ReviewRepository interface.
type MockReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReviewRepositoryMockRecorder
}

// MockReviewRepositoryMockRecorder is the mock recorder for MockReviewRepository.
type MockReviewRepositoryMockRecorder struct {
	mock *MockReviewRepository
}

// NewMockReviewRepository creates a new mock instance.
func NewMockReviewRepository(ctrl *gomock.Controller) *MockReviewRepository {
	mock := &MockReviewRepository{ctrl: ctrl}
	mock.recorder = &MockReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewRepository) EXPECT() *MockReviewRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewRepository) Create(ctx context.Context, r structs.Review) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReviewRepositoryMockRecorder) Create(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewRepository)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockReviewRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewRepository)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockReviewRepository) GetById(ctx context.Context, id uuid.UUID) (structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockReviewRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockReviewRepository)(nil).GetById), ctx, id)
}

// ReviewsForProduct mocks base method.
func (m *MockReviewRepository) ReviewsForProduct(ctx context.Context, id_product uuid.UUID) ([]structs.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewsForProduct", ctx, id_product)
	ret0, _ := ret[0].([]structs.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewsForProduct indicates an expected call of ReviewsForProduct.
func (mr *MockReviewRepositoryMockRecorder) ReviewsForProduct(ctx, id_product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewsForProduct", reflect.TypeOf((*MockReviewRepository)(nil).ReviewsForProduct), ctx, id_product)
}
