// Code generated by MockGen. DO NOT EDIT.
// Source: service/basket/basket.go

// Package mock_structs is a generated GoMock package.
package mock_structs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockBasketService is a mock of BasketService interface.
type MockBasketService struct {
	ctrl     *gomock.Controller
	recorder *MockBasketServiceMockRecorder
}

// MockBasketServiceMockRecorder is the mock recorder for MockBasketService.
type MockBasketServiceMockRecorder struct {
	mock *MockBasketService
}

// NewMockBasketService creates a new mock instance.
func NewMockBasketService(ctrl *gomock.Controller) *MockBasketService {
	mock := &MockBasketService{ctrl: ctrl}
	mock.recorder = &MockBasketServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketService) EXPECT() *MockBasketServiceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockBasketService) AddItem(ctx context.Context, i structs.BasketItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockBasketServiceMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockBasketService)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockBasketService) Create(ctx context.Context, b structs.Basket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBasketServiceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBasketService)(nil).Create), ctx, b)
}

// DeleteItem mocks base method.
func (m *MockBasketService) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockBasketServiceMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockBasketService)(nil).DeleteItem), ctx, id, product_id)
}

// GetById mocks base method.
func (m *MockBasketService) GetById(ctx context.Context, id uuid.UUID) (structs.Basket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Basket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBasketServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBasketService)(nil).GetById), ctx, id)
}

// GetItems mocks base method.
func (m *MockBasketService) GetItems(ctx context.Context, id_basket uuid.UUID) ([]structs.BasketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_basket)
	ret0, _ := ret[0].([]structs.BasketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockBasketServiceMockRecorder) GetItems(ctx, id_basket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockBasketService)(nil).GetItems), ctx, id_basket)
}

// UpdateItemAmount mocks base method.
func (m *MockBasketService) UpdateItemAmount(ctx context.Context, user_id, product_id uuid.UUID, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemAmount", ctx, user_id, product_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemAmount indicates an expected call of UpdateItemAmount.
func (mr *MockBasketServiceMockRecorder) UpdateItemAmount(ctx, user_id, product_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemAmount", reflect.TypeOf((*MockBasketService)(nil).UpdateItemAmount), ctx, user_id, product_id, amount)
}

// MockBasketRepository is a mock of BasketRepository interface.
type MockBasketRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBasketRepositoryMockRecorder
}

// MockBasketRepositoryMockRecorder is the mock recorder for MockBasketRepository.
type MockBasketRepositoryMockRecorder struct {
	mock *MockBasketRepository
}

// NewMockBasketRepository creates a new mock instance.
func NewMockBasketRepository(ctrl *gomock.Controller) *MockBasketRepository {
	mock := &MockBasketRepository{ctrl: ctrl}
	mock.recorder = &MockBasketRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketRepository) EXPECT() *MockBasketRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockBasketRepository) AddItem(ctx context.Context, i structs.BasketItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockBasketRepositoryMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockBasketRepository)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockBasketRepository) Create(ctx context.Context, b structs.Basket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBasketRepositoryMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBasketRepository)(nil).Create), ctx, b)
}

// DeleteItem mocks base method.
func (m *MockBasketRepository) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockBasketRepositoryMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockBasketRepository)(nil).DeleteItem), ctx, id, product_id)
}

// GetBIdByUId mocks base method.
func (m *MockBasketRepository) GetBIdByUId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBIdByUId", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBIdByUId indicates an expected call of GetBIdByUId.
func (mr *MockBasketRepositoryMockRecorder) GetBIdByUId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBIdByUId", reflect.TypeOf((*MockBasketRepository)(nil).GetBIdByUId), ctx, id)
}

// GetById mocks base method.
func (m *MockBasketRepository) GetById(ctx context.Context, id uuid.UUID) (structs.Basket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Basket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBasketRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBasketRepository)(nil).GetById), ctx, id)
}

// GetItems mocks base method.
func (m *MockBasketRepository) GetItems(ctx context.Context, id_basket uuid.UUID) ([]structs.BasketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_basket)
	ret0, _ := ret[0].([]structs.BasketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockBasketRepositoryMockRecorder) GetItems(ctx, id_basket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockBasketRepository)(nil).GetItems), ctx, id_basket)
}

// UpdateItemAmount mocks base method.
func (m *MockBasketRepository) UpdateItemAmount(ctx context.Context, basket_id, product_id uuid.UUID, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemAmount", ctx, basket_id, product_id, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItemAmount indicates an expected call of UpdateItemAmount.
func (mr *MockBasketRepositoryMockRecorder) UpdateItemAmount(ctx, basket_id, product_id, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemAmount", reflect.TypeOf((*MockBasketRepository)(nil).UpdateItemAmount), ctx, basket_id, product_id, amount)
}
