// Code generated by MockGen. DO NOT EDIT.
// Source: service/favourites/favourites.go

// Package mock_structs is a generated GoMock package.
package mock_structs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockFavouritesService is a mock of FavouritesService interface.
type MockFavouritesService struct {
	ctrl     *gomock.Controller
	recorder *MockFavouritesServiceMockRecorder
}

// MockFavouritesServiceMockRecorder is the mock recorder for MockFavouritesService.
type MockFavouritesServiceMockRecorder struct {
	mock *MockFavouritesService
}

// NewMockFavouritesService creates a new mock instance.
func NewMockFavouritesService(ctrl *gomock.Controller) *MockFavouritesService {
	mock := &MockFavouritesService{ctrl: ctrl}
	mock.recorder = &MockFavouritesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavouritesService) EXPECT() *MockFavouritesServiceMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockFavouritesService) AddItem(ctx context.Context, i structs.FavouritesItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockFavouritesServiceMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockFavouritesService)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockFavouritesService) Create(ctx context.Context, b structs.Favourites) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFavouritesServiceMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFavouritesService)(nil).Create), ctx, b)
}

// DeleteItem mocks base method.
func (m *MockFavouritesService) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockFavouritesServiceMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockFavouritesService)(nil).DeleteItem), ctx, id, product_id)
}

// GetById mocks base method.
func (m *MockFavouritesService) GetById(ctx context.Context, id uuid.UUID) (structs.Favourites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Favourites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockFavouritesServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockFavouritesService)(nil).GetById), ctx, id)
}

// GetItems mocks base method.
func (m *MockFavouritesService) GetItems(ctx context.Context, id_Favourites uuid.UUID) ([]structs.FavouritesItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_Favourites)
	ret0, _ := ret[0].([]structs.FavouritesItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockFavouritesServiceMockRecorder) GetItems(ctx, id_Favourites interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockFavouritesService)(nil).GetItems), ctx, id_Favourites)
}

// MockFavouritesRepository is a mock of FavouritesRepository interface.
type MockFavouritesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFavouritesRepositoryMockRecorder
}

// MockFavouritesRepositoryMockRecorder is the mock recorder for MockFavouritesRepository.
type MockFavouritesRepositoryMockRecorder struct {
	mock *MockFavouritesRepository
}

// NewMockFavouritesRepository creates a new mock instance.
func NewMockFavouritesRepository(ctrl *gomock.Controller) *MockFavouritesRepository {
	mock := &MockFavouritesRepository{ctrl: ctrl}
	mock.recorder = &MockFavouritesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavouritesRepository) EXPECT() *MockFavouritesRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockFavouritesRepository) AddItem(ctx context.Context, i structs.FavouritesItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockFavouritesRepositoryMockRecorder) AddItem(ctx, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockFavouritesRepository)(nil).AddItem), ctx, i)
}

// Create mocks base method.
func (m *MockFavouritesRepository) Create(ctx context.Context, b structs.Favourites) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFavouritesRepositoryMockRecorder) Create(ctx, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFavouritesRepository)(nil).Create), ctx, b)
}

// DeleteItem mocks base method.
func (m *MockFavouritesRepository) DeleteItem(ctx context.Context, id, product_id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id, product_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockFavouritesRepositoryMockRecorder) DeleteItem(ctx, id, product_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockFavouritesRepository)(nil).DeleteItem), ctx, id, product_id)
}

// GetById mocks base method.
func (m *MockFavouritesRepository) GetById(ctx context.Context, id uuid.UUID) (structs.Favourites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Favourites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockFavouritesRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockFavouritesRepository)(nil).GetById), ctx, id)
}

// GetFIdByUId mocks base method.
func (m *MockFavouritesRepository) GetFIdByUId(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFIdByUId", ctx, id)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFIdByUId indicates an expected call of GetFIdByUId.
func (mr *MockFavouritesRepositoryMockRecorder) GetFIdByUId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFIdByUId", reflect.TypeOf((*MockFavouritesRepository)(nil).GetFIdByUId), ctx, id)
}

// GetItems mocks base method.
func (m *MockFavouritesRepository) GetItems(ctx context.Context, id_favourites uuid.UUID) ([]structs.FavouritesItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItems", ctx, id_favourites)
	ret0, _ := ret[0].([]structs.FavouritesItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockFavouritesRepositoryMockRecorder) GetItems(ctx, id_favourites interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockFavouritesRepository)(nil).GetItems), ctx, id_favourites)
}
