// Code generated by MockGen. DO NOT EDIT.
// Source: service/worker/worker.go

// Package mock_structs is a generated GoMock package.
package mock_structs

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	structs "github.com/taucuya/ppo/internal/core/structs"
)

// MockWorkerService is a mock of WorkerService interface.
type MockWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServiceMockRecorder
}

// MockWorkerServiceMockRecorder is the mock recorder for MockWorkerService.
type MockWorkerServiceMockRecorder struct {
	mock *MockWorkerService
}

// NewMockWorkerService creates a new mock instance.
func NewMockWorkerService(ctrl *gomock.Controller) *MockWorkerService {
	mock := &MockWorkerService{ctrl: ctrl}
	mock.recorder = &MockWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerService) EXPECT() *MockWorkerServiceMockRecorder {
	return m.recorder
}

// AcceptOrder mocks base method.
func (m *MockWorkerService) AcceptOrder(ctx context.Context, id_order, id_worker uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptOrder", ctx, id_order, id_worker)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptOrder indicates an expected call of AcceptOrder.
func (mr *MockWorkerServiceMockRecorder) AcceptOrder(ctx, id_order, id_worker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptOrder", reflect.TypeOf((*MockWorkerService)(nil).AcceptOrder), ctx, id_order, id_worker)
}

// Create mocks base method.
func (m *MockWorkerService) Create(ctx context.Context, w structs.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkerServiceMockRecorder) Create(ctx, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkerService)(nil).Create), ctx, w)
}

// Delete mocks base method.
func (m *MockWorkerService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkerServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkerService)(nil).Delete), ctx, id)
}

// GetAllWorkers mocks base method.
func (m *MockWorkerService) GetAllWorkers(ctx context.Context) ([]structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWorkers", ctx)
	ret0, _ := ret[0].([]structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWorkers indicates an expected call of GetAllWorkers.
func (mr *MockWorkerServiceMockRecorder) GetAllWorkers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWorkers", reflect.TypeOf((*MockWorkerService)(nil).GetAllWorkers), ctx)
}

// GetById mocks base method.
func (m *MockWorkerService) GetById(ctx context.Context, id uuid.UUID) (structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockWorkerServiceMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockWorkerService)(nil).GetById), ctx, id)
}

// GetOrders mocks base method.
func (m *MockWorkerService) GetOrders(ctx context.Context, id uuid.UUID) ([]structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, id)
	ret0, _ := ret[0].([]structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockWorkerServiceMockRecorder) GetOrders(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockWorkerService)(nil).GetOrders), ctx, id)
}

// MockWorkerRepository is a mock of WorkerRepository interface.
type MockWorkerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerRepositoryMockRecorder
}

// MockWorkerRepositoryMockRecorder is the mock recorder for MockWorkerRepository.
type MockWorkerRepositoryMockRecorder struct {
	mock *MockWorkerRepository
}

// NewMockWorkerRepository creates a new mock instance.
func NewMockWorkerRepository(ctrl *gomock.Controller) *MockWorkerRepository {
	mock := &MockWorkerRepository{ctrl: ctrl}
	mock.recorder = &MockWorkerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerRepository) EXPECT() *MockWorkerRepositoryMockRecorder {
	return m.recorder
}

// AcceptOrder mocks base method.
func (m *MockWorkerRepository) AcceptOrder(ctx context.Context, id_order, id_worker uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptOrder", ctx, id_order, id_worker)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptOrder indicates an expected call of AcceptOrder.
func (mr *MockWorkerRepositoryMockRecorder) AcceptOrder(ctx, id_order, id_worker interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptOrder", reflect.TypeOf((*MockWorkerRepository)(nil).AcceptOrder), ctx, id_order, id_worker)
}

// Create mocks base method.
func (m *MockWorkerRepository) Create(ctx context.Context, w structs.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWorkerRepositoryMockRecorder) Create(ctx, w interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkerRepository)(nil).Create), ctx, w)
}

// Delete mocks base method.
func (m *MockWorkerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkerRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkerRepository)(nil).Delete), ctx, id)
}

// GetAllWorkers mocks base method.
func (m *MockWorkerRepository) GetAllWorkers(ctx context.Context) ([]structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllWorkers", ctx)
	ret0, _ := ret[0].([]structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllWorkers indicates an expected call of GetAllWorkers.
func (mr *MockWorkerRepositoryMockRecorder) GetAllWorkers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllWorkers", reflect.TypeOf((*MockWorkerRepository)(nil).GetAllWorkers), ctx)
}

// GetById mocks base method.
func (m *MockWorkerRepository) GetById(ctx context.Context, id uuid.UUID) (structs.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(structs.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockWorkerRepositoryMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockWorkerRepository)(nil).GetById), ctx, id)
}

// GetOrders mocks base method.
func (m *MockWorkerRepository) GetOrders(ctx context.Context, id uuid.UUID) ([]structs.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, id)
	ret0, _ := ret[0].([]structs.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockWorkerRepositoryMockRecorder) GetOrders(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockWorkerRepository)(nil).GetOrders), ctx, id)
}
